### ISSUE TITLE
Tickets to keep an eye on

### ISSUE THREAD

**Issue by binarymist** [purpleteam-labs/purpleteam#13]
* [x] purpleteam build failing due to [`code --coverage`](https://github.com/hapijs/lab/issues/999)
* [x] Chase AWS around security testing compliance
* [ ] From issue [Update Packages](https://github.com/purpleteam-labs/purpleteam/issues/29) gherkin (currently required to support [cucumber-redacted.js](https://gitlab.com/purpleteam-labs/purpleteam-app-scanner/-/blob/9be05624afc9a92ebe89da9cc82e16dd856c562d/src/scripts/cucumber-redacted.js)). [Issue submitted](https://github.com/cucumber/cucumber-js/issues/1489), waiting for response. Currently working on app-scanner branch `binarymist/cucumber-redacted-removal`
  Useful Resources:  
  * [TypeError: Gherkin.fromPaths is not a function](https://github.com/cucumber/cucumber/issues/857)
  * [Cucumber mono repo Changelog](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md)
  * [Cucumber Tags](https://cucumber.io/docs/cucumber/api/#tags)
  * [Conditionally adding entries inside Array and object literals](https://2ality.com/2017/04/conditional-literal-entries.html)
  * [await vs return vs return await](https://jakearchibald.com/2017/await-vs-return-vs-return-await/)  
  
  Todo:  
  
  * [x] Test different tag configurations
  * [x] Write Tests
  * [x] Check that coverage is working
  * [ ] Waiting for answer to the removed `cucumber.getTestCasesFromFilesystem` functionality which causes [tests to fail](https://github.com/purpleteam-labs/purpleteam-app-scanner/blob/main/test/api/app/models/app.js#L59-L93). [issue](https://github.com/cucumber/cucumber-js/issues/1489)
  * [x] New `on` function expected on `cucumberCliStdout` that's used to instantiate the cucumber Cli. [Introduced in @cucumber/cucumber 7.1.0](https://github.com/cucumber/cucumber-js/issues/1689)
* [x] Can not upgrade from "@cucumber/gherkin": "17.0.2" to "@cucumber/gherkin-streams": "2.0.2" https://github.com/cucumber/cucumber-js/issues/1675
* [x] `gotPt.defaults` [having to be reset](https://github.com/sindresorhus/got/issues/1571) in the CLI
